[package]
name = "my_specs_game"
version = "0.1.0"
edition = "2021"

[dependencies]
specs = "0.20.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
