dt: 0.5
table:
  width: 127.0
  height: 254.0
#head_spot: # 手球の初期位置とするために削除
#  x: 63.5
#  y: 127.0
ball:
  radius: 5.7
  # vx: 8.0 # 手球の初期速度とするために削除
  # vy: 8.0 # 手球の初期速度とするために削除
  mass: 170.0
  restitution: 0.9
cue_ball:
  x: 63.5 # 手球の初期位置x
  y: 127.0 # 手球の初期位置x
  vx: 8.0 # 手球の初期速度vx m/s（内部では 8.0 * 100 = 800 cm/s に変換）
  vy: 8.0 # 手球の初期速度vy  m/s
object_balls:
  positions:
    - { x: 63.5, y: 117.0 } # 1行目：1球
    - { x: 58.5, y: 122.0 } # 2行目：左側の球
    - { x: 68.5, y: 122.0 } # 2行目：右側の球
    - { x: 53.5, y: 127.0 } # 3行目：左から1番目
    - { x: 63.5, y: 127.0 } # 3行目：中央の球（通常は9番目となる場合もあります）
    - { x: 73.5, y: 127.0 } # 3行目：右から1番目
    - { x: 58.5, y: 132.0 } # 4行目：左側の球
    - { x: 68.5, y: 132.0 } # 4行目：右側の球
    - { x: 63.5, y: 137.0 } # 5行目：1球
